//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JinRi.Notify.ServiceAgent.ReceiverReceiveServiceSOA {
    using System;
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessagePriorityEnum", Namespace="http://schemas.datacontract.org/2004/07/JinRi.Notify.Model")]
    public enum MessagePriorityEnum : byte {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Middle = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="PushResultEnum", Namespace="http://schemas.datacontract.org/2004/07/JinRi.Notify.Model")]
    public enum PushResultEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Abort = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pushing = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReceiverReceiveServiceSOA.IReceiveService")]
    public interface IReceiveService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveService/Notify", ReplyAction="http://tempuri.org/IReceiveService/NotifyResponse")]
        JinRi.Notify.DTO.NotifyMessageResult Notify(JinRi.Notify.DTO.NotifyMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveService/Notify", ReplyAction="http://tempuri.org/IReceiveService/NotifyResponse")]
        System.Threading.Tasks.Task<JinRi.Notify.DTO.NotifyMessageResult> NotifyAsync(JinRi.Notify.DTO.NotifyMessage message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReceiveServiceChannel : JinRi.Notify.ServiceAgent.ReceiverReceiveServiceSOA.IReceiveService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceiveServiceClient : System.ServiceModel.ClientBase<JinRi.Notify.ServiceAgent.ReceiverReceiveServiceSOA.IReceiveService>, JinRi.Notify.ServiceAgent.ReceiverReceiveServiceSOA.IReceiveService {
        
        public ReceiveServiceClient() {
        }
        
        public ReceiveServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceiveServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JinRi.Notify.DTO.NotifyMessageResult Notify(JinRi.Notify.DTO.NotifyMessage message) {
            return base.Channel.Notify(message);
        }
        
        public System.Threading.Tasks.Task<JinRi.Notify.DTO.NotifyMessageResult> NotifyAsync(JinRi.Notify.DTO.NotifyMessage message) {
            return base.Channel.NotifyAsync(message);
        }
    }
}
